### ISSUE TITLE
Code version release management

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#101]
We work in an enterprise environment and would like to understand how the frontend and backend code versions are updated in case of future updates.

Moreover, the `deploy.ps1` script is not idempotent and doesn't store the state of the infra, and it would be good to move this to Terraform and provide some sample pipelines to build, publish and consume app container images.

**Comment by DCMattyG** [comment]
Lots of great feedback @jeevanions!

Right now, we're in the building phase of the Azure IPAM tool, attempting to rapidly get all of the core/key features into the platform. As such, releases are sporadic with functionality coming out as fast as we can code it. When we push new code to the **main** branch, we also push new container to our hosted registry with the updated builds. For users who have deployed the solution from our script (without the Private ACR), they can simply restart their App Service and the updated containers will be pulled down.

In the (hopefully near) future, we plan of having GitHub Actions and build pipelines for release management so that we can have a reliable schedule of when new releases are expected.

I hope that helps to answer your question, but please let me know if any additional detail is required here. Always happy to chat 1:1 live if that is more desirable. Thanks!

**Comment by jeevanions** [comment]
I totally love it hence these questions. I have demoed this to our client, and they are impressed. They have all the things needed out of the box.  We are planning to deploy it in a production environment and start using it. So we have to figure out how the control the release and updates, etc.
Thank you for your hard work.

**Comment by DCMattyG** [comment]
Hi @jeevanions, I know it's been a really long time coming, but this ask has now been implemented as of #230.

You'll start seeing a versioned release with every PR merge back to main. Hope this aligns with your original ask, and please let me know if you have any follow-up questions or issues around this.

Have a great one!
