### ISSUE TITLE
Admin option no longer available

### ISSUE THREAD

**Issue by thudgen** [Azure/ipam#154]
When I log in with privileged account admin option is no longer available. The first time I logged in it was there, and I added a couple of spaces, now it is not there, and I can no longer add spaces.

**Comment by DCMattyG** [comment]
Hi @thudgen, nice to meet you!

When you say "privileged account", do you mean in the Azure sense, or do you mean that you explicitly added this user as an Admin within the IPAM UI?

The way Azure IPAM handles Admins is by remember the Object ID's of users and/or principals that were added as Admins. When you first login to the tool and no Admins are defined, everyone is essentially an Admin. Once you define Admins, only those users can access the Admin features.

If you believe that somehow you were accidentally locked out (for whatever reason), one solution could be to go into the Cosmos DB database and remove the Admins, setting it back to the "everyone is an Admin" mode. I'm happy to provide some screenshots and guidance around this process, or I'm also happy to setup a quick Teams meeting to walk you through the process myself.

What works best for you? We're here to help!

**Comment by DCMattyG** [comment]
Good morning @thudgen, as it's been a while since this case was opened and I haven't heard back from you I'm going to close this issue for now.

If you're still experiencing this issue, let us know and we are more than happy to assist you however we can. Please do not hesitate to reach out again via GitHub, or you can also contact me directly via my email at Matthew.Garrett@microsoft.com if that is more comfortable for you. We can absolutely re-open this issue in the future if required.

I hope you have a great experience with the Azure IPAM project, we're always here if there's ever any other assistance you may need!

**Comment by thudgen** [comment]
I re-installed and it is working.


Terrence K. Hudgen
Deputy Chief Technology Officer
Office of the Chief Information Officer
Small Business Administration


Office (202) 205-6384
Cell (202) 440-3953
E-Mail ***@***.***

Non avere peli sulla lingua

**Comment by DCMattyG** [comment]
Great to hear @thudgen, thank you so much for following-up with me on that. Have a great day!
