### ISSUE TITLE
IPAM just returns a white page.

### ISSUE THREAD

**Issue by GeordieGuy** [Azure/ipam#155]
IPAM page just shows white screen. There is HTML getting returned (there is a title for the page for example) but nothing else in the page.

**To Reproduce**
1. Go to the address

**Expected behavior**
The IPAM front end shows, the picture of "PAM"

**Screenshots**
Imagine white. That.

The actual content returned is;

<!doctype html><html lang="en"><head><meta charset="utf-8"/><script type="text/javascript" src="[/env.js](view-source:https://ipam.prd.boq.com.au/env.js)"></script><link rel="icon" type="image/png" sizes="32x32" href="[/favicon-32x32.png](view-source:https://ipam.prd.boq.com.au/favicon-32x32.png)"><link rel="icon" type="image/png" sizes="16x16" href="[/favicon-16x16.png](view-source:https://ipam.prd.boq.com.au/favicon-16x16.png)"><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" sizes="180x180" href="[/apple-touch-icon.png](view-source:https://ipam.prd.boq.com.au/apple-touch-icon.png)"><link rel="manifest" href="[/site.webmanifest](view-source:https://ipam.prd.boq.com.au/site.webmanifest)"><link href="[https://fonts.googleapis.com/icon?family=Material+Icons](view-source:https://fonts.googleapis.com/icon?family=Material+Icons)" rel="stylesheet"><title>Azure IPAM</title><script defer="defer" src="[/static/js/main.65ea9fde.js](view-source:https://ipam.prd.boq.com.au/static/js/main.65ea9fde.js)"></script><link href="[/static/css/main.86f07869.css](view-source:https://ipam.prd.boq.com.au/static/css/main.86f07869.css)" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

**Comment by DCMattyG** [comment]
Hi @GeordieGuy, really appreciate you reaching out. I can't definitely imagine white, so I've got you covered 😉 

The most common reason for this is because the user whom ran the Deployment script didn't have one of the necessary permission which allowed them to grant access to the App Registrations that are created during deployment. This results in some failed calls.

To start, I do want to make sure you had a chance to review the perquisites that we have [here](https://azure.github.io/ipam/#/deployment/README?id=prerequisites) in the docs page.

Additionally, there should've been a **logs** folder created during deployment, and that may hold more information as to what, if anything, failed during the deployment. You may also see failures in the Web Developer Tools of your browser in either the **console** or **network** sections.

Finally, I am *more than happy* to meet with you 1:1 to assist you through any issues you might be experiencing. If you're interesting in that path, please don't hesitate to reach out to me at Matthew.Garrett@microsoft.com and I'll get an invite out to you right away at a time that is convenient for you (and your time zone).

**Comment by DCMattyG** [comment]
Hi @GeordieGuy, hoping all is well with you sir!

We spoke a few weeks back via Teams to discuss a resolution to this issue, and I just wanted to make sure that everything is back running in a healthy state for you or if there's anything else that I can do for you to assist.

If everything is back to normal, please let me know so I can close out this issue.

Thanks so much, have a wonderful rest of the week!

**Comment by DCMattyG** [comment]
Good morning @GeordieGuy, as it's been a while since this issue was opened, and we spoke live to resolve this issue, I'm going to close this for now.

As always, if you have any further issues please don't hesitate to reach out here on GitHub, or directly to me at my email address above and I'm more than happy to help you out. We can also re-open this issue if required in the future.

Thank you and I hope you have a wonderful experience with the Azure IPAM project!
