### ISSUE TITLE
API to get block networks /api/spaces/{space}/blocks/{block}/available or /api/spaces/{space}/blocks/{block}/networks response schema doesn't match  swagger UI 

### ISSUE THREAD

**Issue by nagachakithmck** [Azure/ipam#169]
**Describe the bug**
API to get block associated networks /api/spaces/{space}/blocks/{block}/available or /api/spaces/{space}/blocks/{block}/networks response schema doesn't match  swagger UI 

**To Reproduce**
1. query api API to get /api/spaces/{space}/blocks/{block}/available or /api/spaces/{space}/blocks/{block}/networks
2. check the response 
3. response schema :  [ { "id" : "", "active" : ""}, { "id" : "", "active" : ""}]

**Expected behavior**
as per swagger UI , response should match schema 

[
  {
    "name": "string",
    "id": "string",
    "prefixes": [
      "string"
    ],
    "resource_group": "string",
    "subscription_id": "string",
    "tenant_id": "string"
  }
]

**Comment by DCMattyG** [comment]
Hi @nagachakithmck, the response is a Union of multiple possible Schemas depending on if you use the **expand** flag or not. What you are referring to is the *example* response within the Swagger UI. However, if you select **Schema** instead of **Example Value**, you will see all of the possible Schemas for the given API.

Example:
![image](https://github.com/Azure/ipam/assets/12955732/671c79fe-ed86-4417-b490-a9fcf768e3df)

I hope that helps clear things up a bit for you!

**Comment by nagachakithmck** [comment]
Hi @DCMattyG  , i get response : [ { "id" : "", "active" : ""}, { "id" : "", "active" : ""}] when i try it from postman. 
is this expected  ?

**Comment by DCMattyG** [comment]
If you are not adding the **expand** query string, then yes it is.

![image](https://github.com/Azure/ipam/assets/12955732/3bf342e8-0bc7-42f8-81ff-b17096439569)

> https://ipam.azurewebsites.net/api/spaces/TestSpace/blocks/TestBlock/networks?expand=true

**Comment by DCMattyG** [comment]
It's always my pleasure. Please let me know if there's anything else I can do for you.
