### ISSUE TITLE
Block Network Associations - Not all VNets are showing

### ISSUE THREAD

**Issue by pjbritz** [Azure/ipam#178]
**Describe the bug**
We have a large environment with more than 140 Vnets in a single CIDR block. The problem is that when you open up Network Associations for the block it only shows 128 Vnets.
Other blocks with less than 100 Vnets are showing all of the Vnets under the Network Associations .
**To Reproduce**
1. Go to 'Vnets' and count the number of Vnets when filtering by block CIDR
2. Go to 'Network Associations' and count the number of Vnets being showed for the block

**Expected behavior**
Need to be able so see all Vnets in the CIDR range in order to Associate them with the Block

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Firefox

**Comment by DCMattyG** [comment]
Hi @pjbritz, thank you so much for reaching out!

I wanted to share with you the criteria for being listed on the **Network Associations** page as a Virtual Network/Hub that can potentially be associated with the target **Block**:

1. The Virtual Network/Hub must be container within the CIDR of the Block
2. The Virtual Network/Hub cannot overlap and *unfulfilled* Reservation
3. The Virtual Network/Hub cannot overlap an attached External Network
4. The Virtual Network/Hub cannot be assigned to another Block within the same Space

So hopefully these criteria may help explain why you are seeing a difference between the overall list of Virtual Networks/Hubs and the filtered list that is shown in **Network Associations**. If for some reason you feel that you are *still* missing some expected Virtual Networks/Hubs from the list in **Network Associations**, I'm more than happy to hop on a quick call with you to explore further why this is happening.

Please feel free to circle back with me here, otherwise you're absolutely welcome to drop me and email at Matthew.Garrett@microsoft.com and we can find a day/time that works best to meet.

Hope all of the above helped, we've got you covered!

**Comment by pjbritz** [comment]
Hi,

Thank you for your response, It was reservations which caused our issues.
