### ISSUE TITLE
Running AppOnly with AsFunction returns error

### ISSUE THREAD

**Issue by JamesWordie** [Azure/ipam#206]
**Describe the bug**
I had successfully previously deployed the Full Deployment version as a POC however, I was keen to experiment with the AppOnly and Function variation, however ran into the following issues.

**To Reproduce**
In the cloudshell, clone the repo, cd into the deploy folder.
Run the deploy.ps1 shell command with the argument's AppOnly and AsFunction 

**Expected behavior**
It deploys the ipam solution

**Screenshots**
Error message and command ran;

PS /home/james/ipam/deploy> ./deploy.ps1 -AppsOnly -AsFunction

NOTE: IPAM Deployment Type: FuncAppsOnly
INFO: Fetching Tenant ID from Azure PowerShell SDK
INFO: Fetching Azure Cloud type from Azure PowerShell SDK
INFO: Creating Azure IPAM Engine Application
INFO: Creating Azure IPAM Engine Service Principal
New-AzRoleAssignment: /usr/local/share/powershell/Modules/Az.Resources/6.11.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:752
Line |
 752 |        $ra = New-AzRoleAssignment @param
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Forbidden'
INFO: Creating Azure IPAM Engine Secret
INFO: Azure IPAM Engine & UI Applications/Service Principals created successfully
INFO: Logging in to Microsoft Graph
INFO: Granting admin consent for Azure Service Management API permissions assigned to IPAM Engine application
INFO: Admin consent for Azure Service Management API permissions granted successfully
INFO: Populating Bicep parameter file for infrastructure deployment
INFO: Bicep parameter file populated successfully
INFO: Azure IPAM Solution deployed successfully

deploy.ps1: Cannot index into a null array.

**Desktop (please complete the following information):**
In the cloudshell on my Azure Account where I am an Admin.

PS /home/james/ipam/deploy> az --version                                                                                                                                    azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.21.1
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/james/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**
Running the command it creates the engine App Reg but that's it before it errors out. If you have any suggestions/fixes it would be appreciated. Thanks

**Comment by DCMattyG** [comment]
Hi there @JamesWordie, appreciate you reaching out to us for some assistance!

Just to make sure it's clear, there are to primary ways to deploy the Azure IPAM solution....

1. Full Deployment (one step), which is a combination of the "AppOnly" and "Infrastructure" steps.
2. Two step deployment in which "AppOnly" is used to deploy only the App Registrations, followed by the infrastructure deployment which takes the Parameter files output from the "AppOnly" step and creates the Azure IPAM resources.

The point of the two step mechanism is where a single team doesn't have the permission to both deploy the App Registrations, and also deploy all of the Azure infrastructure.

So, I believe what you are trying to do is the Function Only deployment. Note, this is API-only and doesn't have a UI like the Full deployment.

The error you are seeing above is because you don't appear to have the permission to assign the Service Principal as a "Reader" on the Root Management Group, hence why you are seeing the 403 "Forbidden". The need for this is spelled out [here](https://azure.github.io/ipam/#/deployment/README?id=prerequisites) in the prerequisites section of the Deployment guide.

I hope the above helped and gives you a better idea on the next steps. As I tell everyone, I'm more than happy to meet with you and/or personally assist should you need me. I can be reached directly at Matthe.Garrett@microsoft.com if you'd like to schedule some time.

Have a great one!

**Comment by JamesWordie** [comment]
Thanks for the prompt reply, and for explaining the error, feel free to close this now, as this has the resolved the issue.

Thanks, James

**Comment by DCMattyG** [comment]
Wonderful to hear @JamesWordie, we're always here to help however we can!
