### ISSUE TITLE
Deploy using Azure Container instances

### ISSUE THREAD

**Issue by lduparc** [Azure/ipam#28]
Is there sample on how to deploy this IPAM solution with Container instances. I'm trying to do it but I've got a blank page when trying to access IPAM running on container instances. I presume issues with JS or something like since it's working locally but not on Azure.

Or linked to CORS, how can we deal with it using ACI?

Any inputs or people already try it ?

Thanks

**Comment by DCMattyG** [comment]
Hi @lduparc, thanks for reaching out! I think this topic is better moved to our GitHub Discussions as it's not actually an issue with the product per-se. That being said, we support IPAM running in Azure App Services today, and very shortly we'll support Azure Functions for API-Only.

We're using App Services/Functions because they put the SSL cert in front of the service as we're not natively using SSL in the containers. Can you help me understand better why you'd prefer this solution running in Azure Container Instances? Is this a cost related ask, or perhaps is there some other business reason that ACI makes sense for you?

We're absolutely open to working to support running this solution in additional Azure services, but we just want to make sure we're prioritizing accordingly. For instance, perhaps Azure Container Apps makes more sense (as opposed to ACI) as you can still use that service to provide SSL on top of the existing containers.

Please share your thoughts, we love the feedback!

**Comment by hmizael** [comment]
Good afternoon everyone,

So I was able to run it through AKS (Azure Kubernetes Services), I really can't tell if it would be similar to running ACI. Even IPAM is not being supported via AKS, but I'm not having any issues. Since ACI is more of a container-as-a-service flavor, it might be the same as this deployment. I will run some tests and see what would be needed step-by-step.

I also hope that IPAM time supports AKS natively.

**Comment by DCMattyG** [comment]
Hi @hmizael, I'm so glad you've got everything working in AKS! I agree that we should add some additional deployment models. @hbendana and I will talk through a plan to start adding things like AKS, Azure Container Apps, and perhaps a few others.

ACI would likely be different since you don't have k8s constructs like ingress controllers, so you'd need to from it with something like App Gateway, or perhaps add an NGINX, HA Proxy, or Traefik container into the mix for the path based routing to the UI or API engine.

**Comment by DCMattyG** [comment]
Ok @hmizael and @lduparc, I'm going to close this issue, and move this to our GitHub discussions section, located here:

https://github.com/Azure/ipam/discussions

Looking forward to continuing this conversation with you!
