### ISSUE TITLE
Request : Terraform Provider

### ISSUE THREAD

**Issue by benoitsautierecellenza** [Azure/ipam#66]
First, thank your for your solution, you respond to a concrete need in Azure Landing zone projects. In fact, the only missing piece in your solution is a Terraform Provider.

Having a Terraform Provider would help to integrate your solution into complex Landing zones deployments.

At minimum, the Terraform provider should offer : 
- Reservation of an IP Range 
- Lease reservation of an IP Range

**Comment by DCMattyG** [comment]
Good morning @benoitsautierecellenza, I agree with you that this is indeed a good idea. It may or may not come to fruition because the end goal of this project is that I'm working with the Azure Networking product group to actually get the IPAM feature built into the platform, and at that time we already have a Terraform provider that should be sufficient.

For now, if you look in the "examples" folder of the repo, I do have a Terraform example of what you described using some scripting. Have you taken a look at that yet?

https://github.com/Azure/ipam/tree/main/examples/ipam-terraform

**Comment by DCMattyG** [comment]
Thank you @benoitsautierecellenza! May I mark this as completed for now, or would you like me to leave it open?

**Comment by benoitsautierecellenza** [comment]
Yes I close.
